/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Enter.Enter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author steyza
 */
public class Main_F extends javax.swing.JFrame {
    static Integer Allapot=null;
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    
    /**
     * Creates new form Main_F
     */
    public Main_F() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Karb = new javax.swing.JMenu();
        jMenuItem_UjFelh = new javax.swing.JMenuItem();
        jMenuItem_UjTermek = new javax.swing.JMenuItem();
        jMenuItem_Tcs = new javax.swing.JMenuItem();
        jMenu_Ugyv = new javax.swing.JMenu();
        jMenuItem_Elad = new javax.swing.JMenuItem();
        jMenuItem_Kimutat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setForeground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        jMenu_Karb.setText("Karbantartás");
        jMenu_Karb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem_UjFelh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem_UjFelh.setText("Új_felhasználó");
        jMenuItem_UjFelh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_UjFelhActionPerformed(evt);
            }
        });
        jMenu_Karb.add(jMenuItem_UjFelh);

        jMenuItem_UjTermek.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem_UjTermek.setText("Új_termék");
        jMenuItem_UjTermek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_UjTermekActionPerformed(evt);
            }
        });
        jMenu_Karb.add(jMenuItem_UjTermek);

        jMenuItem_Tcs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem_Tcs.setText("Új_Termékcsoport");
        jMenuItem_Tcs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_TcsActionPerformed(evt);
            }
        });
        jMenu_Karb.add(jMenuItem_Tcs);

        jMenuBar1.add(jMenu_Karb);

        jMenu_Ugyv.setText("Ügyvitel");
        jMenu_Ugyv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem_Elad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem_Elad.setText("Eladás");
        jMenu_Ugyv.add(jMenuItem_Elad);

        jMenuItem_Kimutat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem_Kimutat.setText("Kimutatás");
        jMenu_Ugyv.add(jMenuItem_Kimutat);

        jMenuBar1.add(jMenu_Ugyv);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        conn=MYSQL_kapcs.ConnectDB();
        //JOptionPane.showMessageDialog(null,Into.F_id);
        String sql="Select * from Felh where F_nev='"+Into.Nev+"'"
                        + " and F_jelsz='"+Into.Jelsz+"'";
        try
        {
            Statement sta=conn.createStatement();
            ResultSet rs=sta.executeQuery(sql);
            rs.next();
            Allapot=(Integer.parseInt(rs.getString("F_tip")));
            if (Allapot==1)
            {
                jMenu_Karb.setEnabled(true);
                jMenuItem_UjFelh.setEnabled(true);
                jMenuItem_UjTermek.setEnabled(true);
                jMenuItem_Tcs.setEnabled(true);
                jMenu_Ugyv.setEnabled(true);
                jMenuItem_Elad.setEnabled(true);
                jMenuItem_Kimutat.setEnabled(true);
            }
            else
            {
                jMenu_Karb.setEnabled(true);
                jMenuItem_UjFelh.setEnabled(false);
                jMenuItem_UjTermek.setEnabled(true);
                jMenuItem_Tcs.setEnabled(true);
                jMenu_Ugyv.setEnabled(true);
                jMenuItem_Elad.setEnabled(true);
                jMenuItem_Kimutat.setEnabled(false);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem_UjFelhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_UjFelhActionPerformed
        Uj_Felhasznalo uf=new Uj_Felhasznalo();
        uf.setVisible(true);
    }//GEN-LAST:event_jMenuItem_UjFelhActionPerformed

    private void jMenuItem_TcsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_TcsActionPerformed
        // Termék csoport felvétele (új termékcsoport létrehozása)
        Uj_Termekcsoport utcs=new Uj_Termekcsoport();
        utcs.setVisible(true);
    }//GEN-LAST:event_jMenuItem_TcsActionPerformed

    private void jMenuItem_UjTermekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_UjTermekActionPerformed
        Uj_Termek ut=new Uj_Termek();
        ut.setVisible(true);
    }//GEN-LAST:event_jMenuItem_UjTermekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_F.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_F.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_F.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_F.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_F().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_Elad;
    private javax.swing.JMenuItem jMenuItem_Kimutat;
    private javax.swing.JMenuItem jMenuItem_Tcs;
    private javax.swing.JMenuItem jMenuItem_UjFelh;
    private javax.swing.JMenuItem jMenuItem_UjTermek;
    private javax.swing.JMenu jMenu_Karb;
    private javax.swing.JMenu jMenu_Ugyv;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
